---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myhpa

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flm
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: resource
      resource:
        name: cpu
        target:
          type: utilization
          averageutilization: 50
