---
apiVersion: v1
kind: PersistantVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: vol-0c07e819ca016bb81
    fsType: ext4
##################################

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc2

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
