---
apiVersion: v1
kind: PersistanceVolume
metadata:
  name: pv1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: vol-0c07e819ca016bb81
    fsType: ext4i
##################################
---
apiVersion: v1
kind: PersistantVolumeClaim
metadata:
  name: pvc1
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 2Gi
~
