apiVersion: v1
kind:  ResourceQuota
metadata:
  name: myreso
  namespace: devops
  namespace: test
spec:
  hard:
    limits.cpu: "20m"
    limits.memory: "20Mi"
    requests.cpu: "10m"
    requests.memory: "10MiResource
