---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2

spec:
  containers:
    - name: cont2
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "5Mi"
          cpu: "5m"
        limits:
          memory: "10Mi"
          cpu: "10m"
